version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    restart: always
    env_file: .env

  semaphore:
    build: ./compose/semaphore
    volumes:
      - "./.data/semaphore/ansible:/home/webserver/ansible"
      - "./.data/semaphore/.ssh:/home/webserver/.ssh"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "80:3000"
    restart: always
    env_file: .env